name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Replace Mirror archive
      run: sudo sed -i "s@http://.*archive.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
    - name: Replace Mirror security
      run: sudo sed -i "s@http://.*security.ubuntu.com@https://mirrors.tuna.tsinghua.edu.cn@g" /etc/apt/sources.list
    - name: update
      run: sudo apt-get update
    - name: install dependency
      run: sudo apt-get install build-essential make gcc-multilib
    - name: make clean
      run: make clean
    - name: make all
      run: make all
