name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install dependency
      run: sudo apt-get install build-essential make gcc-multilib
    - name: make clean
      run: make clean
    - name: make all
      run: make all
    - name: make play
      run: make play
